language: java
sudo: required

cache:
  directories:
    - $HOME/.m2

services:
  - docker

script:
  - mvn clean verify
  - docker build . -t automatewebsite/rancher-config-backup

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - .travis/deploy-image.sh