security:
  user:
    name: admin
    password: secret

git-file-pattern: '.'
git-author-name: rancher-config-backup
git-author-email: noreply@automate.website
git-repository-name: default
git-repository-branch: master
